<?php
  $map = array(            
    'Self' => '1',
    'Client Relative, Friend or Carer' => '2',
    'Client Relative' => '2',
    'Friend or Carer' => '2',        
    'Advocate' => '4',
    'Unrelated' => '4',
    'Health or Social Care Professional (Nurse, Doctor, Physio, etc)' => '3',
    'Local Campaigner' => '4',
    'Journalist' => '4',
    'Local Councillor' => '4',
    'Parliamentarian' => '4',
    'Parliamentary or Political Staff International Stakeholder (i.e. Consumer International CEO or UN Official)' => '4',
    'Other' => '4'
  );
