<?php            
  $map = array(
    'Access to services' => '26',
    'Administration' => '9',
    'Admission' => '10',
    'Booking appointments' => '11',
    'Cancellation' => '12',
    'Diagnosis' => '13',
    'Discharge' => '14',
    'Information providing' => '15',
    'Medication' => '16',
    'N/A' => '17',
    'Prescription' => '18',
    'Referrals' => '19',
    'Service Closure' => '20',
    'Staff Levels' => '21',
    'Staff Training' => '22',
    'Support' => '23',
    'Waiting Times and lists for treatment' => '24',
    'Waiting time to be seen once arrived at appointment' => '25'
   );
