<?php            
  $map = array(
    'https://hwe-wib7.cirz.co.uk/sites/healthwatch.co.uk/files/reports-library/20170201_Newcastle_BME%20involvement%20in%20services.rhd_.pdf' => '',
    'https://hwe-wib7.cirz.co.uk/sites/healthwatch.co.uk/files/reports-library/20170302_Northamptonshire_Homelessness%20and%20acess%20report%20.rhd_.pdf' => '',
    'https://hwe-wib7.cirz.co.uk/sites/healthwatch.co.uk/files/reports-library/20170501_Reading_%20Death%20and%20dying%20end%20of%20life%20care.rhd_.pdf' => '',
    'https://hwe-wib7.cirz.co.uk/sites/healthwatch.co.uk/files/reports-library/20170911_Northamptonshire_pharmacy_survey_report.rhd_.pdf' => '',
    'https://hwe-wib7.cirz.co.uk/sites/healthwatch.co.uk/files/reports-library/20170928_Warrington_GP-Access%20Summary%20REport%20Exploring%20ways%20to%20improve%20access%20and%20share%20best%20practice.rhd_.pdf`' => '',
    'https://hwe-wib7.cirz.co.uk/sites/healthwatch.co.uk/files/reports-library/20171031_%20Lincolnshire-Patient%20Experience%20Report%20%E2%80%93%20October%202017%20.rhd_.pdf' => '',
    'https://hwe-wib7.cirz.co.uk/sites/healthwatch.co.uk/files/reports-library/20171102_Warrington_Intermediate%20CareJourneys.rhd_.pdf' => '',   
    'https://hwe-wib7.cirz.co.uk/sites/healthwatch.co.uk/files/reports-library/20171109_Torbay_Quarterly-Public-FINAL-Report-July-Sept%20Older%20People%20.rhd_.pdf' => ''
  );
