<?php
  $map = array(
    'Homeless people' => '1',
    'People in stigmatised occupations (such as sex workers)' => '2',
    'People who are geographically isolated' => '3',
    'People who are long-term unemployed' => '4',
    'People who live in poverty' => '4',
    'People with limited family or social networks' => '5',
    'People who misuse drugs' => '6',
    'Refugees or asylum seekers' => '7'
  );
