<?php            
  $map = array(
 'Telephone' => 'Telephone',
 'Email' => 'E-mail',
 'Website Feedback' => 'Website Feedback',
 'Meeting' => 'Meeting',
 'Outreach' => 'Outreach',
 'Event' => 'Engagement Event',
 'Social Media' => 'Social Media',
 'Post' => 'Post',
 'Research' => 'Research',
 'Other' => 'Not known',
 'Third Party' => 'Third Party',
 'Visit to provider' => 'Visit to provider',
 'Not known' => 'Not known',
 'Engagement Event' => 'Engagement Event',
 'Guidance / Advice' => 'Guidance/Advice'
  );
